Ob\LogBundle\Entity\Event:
  type: entity
  table: ob_log_entries
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    objectClass:
      type: string
      length: 255
    objectId:
      type: integer
      nullable: true
    type:
      type: string
      length: 25
    env:
      type: string
      length: 10
    createdAt:
      type: datetime
    data:
      type: array
      nullable: true
  lifecycleCallbacks: {  }
